# Autogenerated from /Users/justin/Documents/projects/MLIRTemplate/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
from pathlib import Path
def path(p):
    if not p: return ''
    return str((Path(__file__).parent / p).resolve())


config.llvm_tools_dir = lit_config.substitute("/usr/local/bin")
config.lit_tools_dir = ""
config.mlir_obj_dir = "/Users/justin/Documents/projects/MLIRTemplate"
config.python_executable = ""
config.enable_bindings_python = 0
config.example_src_root = "/Users/justin/Documents/projects/MLIRTemplate"
config.example_obj_root = "/Users/justin/Documents/projects/MLIRTemplate"

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "/Users/justin/Documents/projects/MLIRTemplate/test/lit.cfg.py")
